/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import keeptoo.Drag;

/**
 *
 * @author Олег
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    public MainWindow getMainWindow(){
        return this;
    }
    
    static Settings sett = new Settings();
    Popup popup = new Popup();
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new keeptoo.KGradientPanel();
        btn_synchronize = new keeptoo.KButton();
        btn_setting = new keeptoo.KButton();
        time = new javax.swing.JLabel();
        headline = new javax.swing.JLabel();
        btn_play = new keeptoo.KButton();
        btn_exit = new keeptoo.KButton();
        btn_mini = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setkEndColor(new java.awt.Color(204, 0, 204));
        mainPanel.setkStartColor(new java.awt.Color(0, 204, 204));
        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
        });
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_synchronize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/synchronize-50.png"))); // NOI18N
        btn_synchronize.setToolTipText("");
        btn_synchronize.setEnabled(false);
        btn_synchronize.setFocusPainted(false);
        btn_synchronize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_synchronize.setkAllowTab(false);
        btn_synchronize.setkBorderRadius(40);
        btn_synchronize.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_synchronize.setkFillButton(false);
        btn_synchronize.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_synchronize.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_synchronize.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_synchronize.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_synchronize.setName(""); // NOI18N
        btn_synchronize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_synchronizeMouseClicked(evt);
            }
        });
        btn_synchronize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_synchronizeActionPerformed(evt);
            }
        });
        mainPanel.add(btn_synchronize, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 60, 150));

        btn_setting.setBorder(null);
        btn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/settings-50.png"))); // NOI18N
        btn_setting.setToolTipText("");
        btn_setting.setEnabled(false);
        btn_setting.setFocusable(false);
        btn_setting.setIconTextGap(40);
        btn_setting.setkAllowTab(false);
        btn_setting.setkBorderRadius(40);
        btn_setting.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_setting.setkFillButton(false);
        btn_setting.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_setting.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_setting.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_setting.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_setting.setName(""); // NOI18N
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_settingMouseClicked(evt);
            }
        });
        mainPanel.add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 130, 120));

        time.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText(" 30:00");
        time.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mainPanel.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 380, 60));

        headline.setFont(new java.awt.Font("Candara", 0, 48)); // NOI18N
        headline.setForeground(new java.awt.Color(204, 204, 204));
        headline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headline.setText("TrainBrain");
        mainPanel.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 260, 50));

        btn_play.setBorder(null);
        btn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/play-50.png"))); // NOI18N
        btn_play.setToolTipText("");
        btn_play.setFocusable(false);
        btn_play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_play.setkAllowTab(false);
        btn_play.setkBorderRadius(40);
        btn_play.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_play.setkFillButton(false);
        btn_play.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_play.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_play.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_play.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_playMouseClicked(evt);
            }
        });
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        mainPanel.add(btn_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 60, 150));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/delete-25.png"))); // NOI18N
        btn_exit.setToolTipText("");
        btn_exit.setDoubleBuffered(true);
        btn_exit.setFocusPainted(false);
        btn_exit.setIconTextGap(0);
        btn_exit.setkAllowTab(false);
        btn_exit.setkBorderRadius(40);
        btn_exit.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkPressedColor(new java.awt.Color(255, 51, 51));
        btn_exit.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_exit.setName(""); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        mainPanel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 25, 60));

        btn_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/minimize-25.png"))); // NOI18N
        btn_mini.setToolTipText("");
        btn_mini.setBorderPainted(false);
        btn_mini.setEnabled(false);
        btn_mini.setFocusPainted(false);
        btn_mini.setFocusable(false);
        btn_mini.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mini.setIconTextGap(0);
        btn_mini.setkAllowTab(false);
        btn_mini.setkBorderRadius(40);
        btn_mini.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_mini.setkFillButton(false);
        btn_mini.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_mini.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_mini.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_mini.setkStartColor(new java.awt.Color(204, 204, 204));
        btn_mini.setName(""); // NOI18N
        btn_mini.setOpaque(false);
        btn_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_miniMouseClicked(evt);
            }
        });
        mainPanel.add(btn_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 25, 60));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_synchronizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_synchronizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_synchronizeActionPerformed

    private void mainPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged
        new Drag(mainPanel).moveWindow(evt);
    }//GEN-LAST:event_mainPanelMouseDragged

    private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        new Drag(mainPanel).onPress(evt);
    }//GEN-LAST:event_mainPanelMousePressed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_playActionPerformed
    int min;
    int sec;
    Timer timer = null;
    private void btn_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playMouseClicked
        if(timer!=null)
        timer.cancel();
        timer=null;
        int delay = 1000;
        int period = 1000;
        if(timer==null)
        timer = new Timer();
        min = sett.getMin();
        sec = sett.getSec();
        timer.scheduleAtFixedRate(new TimerTask() {
        public void run() {
            time(timer);
            if(sec<10&&sec>=0)
            time.setText(min+":0"+sec);
            else
            time.setText(min+":"+sec);
        }
        }, delay, period);
    }//GEN-LAST:event_btn_playMouseClicked

    public JLabel getTime(){
        return time;
    }
    
    private void btn_synchronizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_synchronizeMouseClicked
        if(timer!=null)
        timer.cancel();
        timer=null;
        if(sett.getSec()<10&&sett.getSec()>=0)
            time.setText(sett.getMin()+":0"+sett.getSec());
            else
            time.setText(sett.getMin()+":"+sett.getSec());
    }//GEN-LAST:event_btn_synchronizeMouseClicked
    
    
    private void btn_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseClicked
        this.setVisible(false);
        sett.setVisible(true);
    }//GEN-LAST:event_btn_settingMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_miniMouseClicked
        this.setState(ICONIFIED); 
    }//GEN-LAST:event_btn_miniMouseClicked
    
    private void time(Timer time){ 
        if(sec!=0)
            --sec;
        else if(min!=0){
            sec=59;
            --min;
        }
        else{
            time.cancel();
            popup.setVisible(true);
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_exit;
    private keeptoo.KButton btn_mini;
    private keeptoo.KButton btn_play;
    private keeptoo.KButton btn_setting;
    private keeptoo.KButton btn_synchronize;
    private javax.swing.JLabel headline;
    private keeptoo.KGradientPanel mainPanel;
    public javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
