/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import java.awt.Dimension;
import java.awt.Toolkit;
import keeptoo.Drag;

/**
 *
 * @author Олег
 */
public class Popup extends javax.swing.JFrame {

    /**
     * Creates new form Popup
     */
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private final int WIDTH = (int) screenSize.getWidth();
    private final int HEIGHT = (int) screenSize.getHeight();
    
    public Popup() {
        initComponents();
        this.setLocation(WIDTH-535, HEIGHT-350);
        fillAnswers();
    }
    //TODO підтянути слова і відповідідо питання
    private void fillAnswers(){
        btn_answer1.setText("");
        btn_answer2.setText("");
        btn_answer3.setText("");
        btn_answer4.setText("");
        word.setText("random");
    }

    
    private String [][] words = new String[100][4];
    
    private void fillArray()
    {
        words[0][0]="Car";
        words[0][1]="Машина";
        words[0][2]="Ровер";
        words[0][3]="Ліжко";
        words[0][4]="Бик";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPanel = new keeptoo.KGradientPanel();
        headline = new javax.swing.JLabel();
        headlineTM = new javax.swing.JLabel();
        word = new javax.swing.JLabel();
        btn_answer2 = new keeptoo.KButton();
        btn_answer3 = new keeptoo.KButton();
        btn_answer4 = new keeptoo.KButton();
        btn_answer1 = new keeptoo.KButton();
        btn_exit = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        popupPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                popupPanelMouseDragged(evt);
            }
        });
        popupPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popupPanelMousePressed(evt);
            }
        });
        popupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headline.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        headline.setForeground(new java.awt.Color(204, 204, 204));
        headline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headline.setText("TimeToGo");
        popupPanel.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 260, 50));

        headlineTM.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        headlineTM.setForeground(new java.awt.Color(204, 204, 204));
        headlineTM.setText("TrainBrain");
        popupPanel.add(headlineTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, 30));

        word.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word.setText("WORD");
        popupPanel.add(word, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, 60));

        btn_answer2.setText("answer2");
        btn_answer2.setkAllowTab(false);
        btn_answer2.setkHoverForeGround(new java.awt.Color(51, 153, 0));
        btn_answer2.setkPressedColor(new java.awt.Color(255, 255, 255));
        popupPanel.add(btn_answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, -1));

        btn_answer3.setText("answer3");
        btn_answer3.setkAllowTab(false);
        btn_answer3.setkHoverForeGround(new java.awt.Color(51, 153, 0));
        btn_answer3.setkPressedColor(new java.awt.Color(255, 255, 255));
        popupPanel.add(btn_answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 120, -1));

        btn_answer4.setText("answer4");
        btn_answer4.setkAllowTab(false);
        btn_answer4.setkHoverForeGround(new java.awt.Color(51, 153, 0));
        btn_answer4.setkPressedColor(new java.awt.Color(255, 255, 255));
        popupPanel.add(btn_answer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 110, -1));

        btn_answer1.setText("answer1");
        btn_answer1.setkAllowTab(false);
        btn_answer1.setkHoverForeGround(new java.awt.Color(51, 153, 0));
        btn_answer1.setkPressedColor(new java.awt.Color(255, 255, 255));
        popupPanel.add(btn_answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/delete-25.png"))); // NOI18N
        btn_exit.setToolTipText("");
        btn_exit.setDoubleBuffered(true);
        btn_exit.setFocusPainted(false);
        btn_exit.setIconTextGap(0);
        btn_exit.setkAllowTab(false);
        btn_exit.setkBorderRadius(40);
        btn_exit.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkPressedColor(new java.awt.Color(255, 51, 51));
        btn_exit.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_exit.setName(""); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        popupPanel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 25, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void popupPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupPanelMouseDragged
        new Drag(popupPanel).moveWindow(evt);
    }//GEN-LAST:event_popupPanelMouseDragged

    private void popupPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupPanelMousePressed
        new Drag(popupPanel).onPress(evt);
    }//GEN-LAST:event_popupPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_answer1;
    private keeptoo.KButton btn_answer2;
    private keeptoo.KButton btn_answer3;
    private keeptoo.KButton btn_answer4;
    private keeptoo.KButton btn_exit;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel headlineTM;
    private keeptoo.KGradientPanel popupPanel;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables
}
