/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup;

import javafx.scene.input.DragEvent;
import keeptoo.Drag;

/**
 *
 * @author Олег
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInPanel = new keeptoo.KGradientPanel();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        passLabel = new javax.swing.JLabel();
        btn_signUp = new keeptoo.KButton();
        btn_signIn = new keeptoo.KButton();
        icon = new javax.swing.JLabel();
        orLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        headline = new javax.swing.JLabel();
        btn_exit = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInPanel.setkEndColor(new java.awt.Color(204, 0, 204));
        signInPanel.setkStartColor(new java.awt.Color(0, 204, 204));
        signInPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                signInPanelMouseDragged(evt);
            }
        });
        signInPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInPanelMousePressed(evt);
            }
        });
        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new java.awt.Color(0,0,0,0));
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setToolTipText("");
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username.setCaretColor(new java.awt.Color(204, 0, 255));
        username.setOpaque(false);
        username.setPreferredSize(new java.awt.Dimension(69, 31));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        signInPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 380, 31));

        pass.setBackground(new java.awt.Color(0,0,0,0));
        pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setToolTipText("");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pass.setCaretColor(new java.awt.Color(204, 0, 255));
        pass.setOpaque(false);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        signInPanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 380, 31));

        passLabel.setForeground(new java.awt.Color(204, 204, 204));
        passLabel.setText("password");
        signInPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        btn_signUp.setText("SignUp");
        btn_signUp.setToolTipText("");
        btn_signUp.setDoubleBuffered(true);
        btn_signUp.setFocusPainted(false);
        btn_signUp.setkAllowTab(false);
        btn_signUp.setkBorderRadius(40);
        btn_signUp.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_signUp.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_signUp.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_signUp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_signUp.setkPressedColor(new java.awt.Color(204, 102, 255));
        btn_signUp.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_signUp.setName(""); // NOI18N
        btn_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signUpMouseClicked(evt);
            }
        });
        signInPanel.add(btn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 40));

        btn_signIn.setBorder(null);
        btn_signIn.setText("SignIn");
        btn_signIn.setFocusable(false);
        btn_signIn.setkAllowTab(false);
        btn_signIn.setkBorderRadius(40);
        btn_signIn.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_signIn.setkFillButton(false);
        btn_signIn.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_signIn.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_signIn.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_signIn.setkStartColor(new java.awt.Color(255, 255, 255));
        btn_signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signInMouseClicked(evt);
            }
        });
        btn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signInActionPerformed(evt);
            }
        });
        signInPanel.add(btn_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, 40));

        icon.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        icon.setForeground(new java.awt.Color(204, 204, 204));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/user-50.png"))); // NOI18N
        signInPanel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 50, 50));

        orLabel.setForeground(new java.awt.Color(204, 204, 204));
        orLabel.setText(" or");
        signInPanel.add(orLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 20, -1));

        userLabel.setForeground(new java.awt.Color(204, 204, 204));
        userLabel.setText("username");
        signInPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        headline.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(204, 204, 204));
        headline.setText("TrainBrain");
        signInPanel.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 40));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup/delete-25.png"))); // NOI18N
        btn_exit.setToolTipText("");
        btn_exit.setDoubleBuffered(true);
        btn_exit.setFocusPainted(false);
        btn_exit.setIconTextGap(0);
        btn_exit.setkAllowTab(false);
        btn_exit.setkBorderRadius(40);
        btn_exit.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkPressedColor(new java.awt.Color(255, 51, 51));
        btn_exit.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_exit.setName(""); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        signInPanel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 25, 60));

        getContentPane().add(signInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void signInPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPanelMouseDragged
        new Drag(signInPanel).moveWindow(evt);
    }//GEN-LAST:event_signInPanelMouseDragged

    private void signInPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPanelMousePressed
        new Drag(signInPanel).onPress(evt);  
    }//GEN-LAST:event_signInPanelMousePressed

    private void btn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signInActionPerformed

    private void btn_signInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signInMouseClicked
        this.setVisible(false);
        maine.getMainWindow().setVisible(true);
    }//GEN-LAST:event_btn_signInMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signUpMouseClicked
        this.setVisible(false);
        signUp.getSignUp().setVisible(true);
    }//GEN-LAST:event_btn_signUpMouseClicked

    MainWindow maine = new MainWindow();
    SignUp signUp = new SignUp();
    
    public SignIn getSignIn(){
        return this;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_exit;
    private keeptoo.KButton btn_signIn;
    private keeptoo.KButton btn_signUp;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel orLabel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passLabel;
    private keeptoo.KGradientPanel signInPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
