package signup;

import keeptoo.Drag;
import java.awt.event.*;

/**
 * @author Олег
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpPanel = new keeptoo.KGradientPanel();
        mail = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();
        btn_signUp = new keeptoo.KButton();
        icon = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        headline = new javax.swing.JLabel();
        btn_exit = new keeptoo.KButton();
        passConfLabel = new javax.swing.JLabel();
        passConfirm = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        passLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        signUpPanel.setkEndColor(new java.awt.Color(204, 0, 204));
        signUpPanel.setkStartColor(new java.awt.Color(0, 204, 204));
        signUpPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                signUpPanelMouseDragged(evt);
            }
        });
        signUpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpPanelMousePressed(evt);
            }
        });
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mail.setBackground(new java.awt.Color(0, 0, 0, 0));
        mail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setToolTipText("");
        mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mail.setCaretColor(new java.awt.Color(204, 0, 255));
        mail.setOpaque(false);
        mail.setPreferredSize(new java.awt.Dimension(69, 31));
        signUpPanel.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 380, 31));

        mailLabel.setForeground(new java.awt.Color(204, 204, 204));
        mailLabel.setText("e-mail");
        signUpPanel.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btn_signUp.setText("SignUp");
        btn_signUp.setToolTipText("");
        btn_signUp.setDoubleBuffered(true);
        btn_signUp.setFocusPainted(false);
        btn_signUp.setkAllowTab(false);
        btn_signUp.setkBorderRadius(40);
        btn_signUp.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_signUp.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btn_signUp.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_signUp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_signUp.setkPressedColor(new java.awt.Color(204, 102, 255));
        btn_signUp.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_signUp.setName(""); // NOI18N
        btn_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signUpMouseClicked(evt);
            }
        });
        signUpPanel.add(btn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 160, 40));

        icon.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        icon.setForeground(new java.awt.Color(204, 204, 204));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-50.png"))); // NOI18N
        signUpPanel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 50, 50));

        userLabel.setForeground(new java.awt.Color(204, 204, 204));
        userLabel.setText("username");
        signUpPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        headline.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(204, 204, 204));
        headline.setText("TrainBrain");
        signUpPanel.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 40));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-25.png"))); // NOI18N
        btn_exit.setToolTipText("");
        btn_exit.setDoubleBuffered(true);
        btn_exit.setFocusPainted(false);
        btn_exit.setIconTextGap(0);
        btn_exit.setkAllowTab(false);
        btn_exit.setkBorderRadius(40);
        btn_exit.setkEndColor(new java.awt.Color(0, 204, 204));
        btn_exit.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        btn_exit.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        btn_exit.setkPressedColor(new java.awt.Color(255, 51, 51));
        btn_exit.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_exit.setName(""); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        signUpPanel.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 25, 60));

        passConfLabel.setForeground(new java.awt.Color(204, 204, 204));
        passConfLabel.setText("confirm password");
        signUpPanel.add(passConfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        passConfirm.setBackground(new java.awt.Color(0, 0, 0, 0));
        passConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passConfirm.setForeground(new java.awt.Color(255, 255, 255));
        passConfirm.setToolTipText("");
        passConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        passConfirm.setCaretColor(new java.awt.Color(204, 0, 255));
        passConfirm.setOpaque(false);
        signUpPanel.add(passConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 380, 31));

        username.setBackground(new java.awt.Color(0, 0, 0, 0));
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setToolTipText("");
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username.setCaretColor(new java.awt.Color(204, 0, 255));
        username.setOpaque(false);
        username.setPreferredSize(new java.awt.Dimension(69, 31));
        signUpPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 380, 31));

        pass.setBackground(new java.awt.Color(0, 0, 0, 0));
        pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setToolTipText("");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pass.setCaretColor(new java.awt.Color(204, 0, 255));
        pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass.setOpaque(false);
        signUpPanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 380, 31));

        passLabel.setForeground(new java.awt.Color(204, 204, 204));
        passLabel.setText("password");
        signUpPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 810, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(signUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 520, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(signUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void signUpPanelMouseDragged(MouseEvent evt) {//GEN-FIRST:event_signUpPanelMouseDragged
        new Drag(signUpPanel).moveWindow(evt);
    }//GEN-LAST:event_signUpPanelMouseDragged

    private void signUpPanelMousePressed(MouseEvent evt) {//GEN-FIRST:event_signUpPanelMousePressed
        new Drag(signUpPanel).onPress(evt);
    }//GEN-LAST:event_signUpPanelMousePressed

    private void btn_signUpMouseClicked(MouseEvent evt) {//GEN-FIRST:event_btn_signUpMouseClicked
        this.setVisible(false);
        maine.getMainWindow().setVisible(true);
    }//GEN-LAST:event_btn_signUpMouseClicked

    SignUp getSignUp() {
        return this;
    }

    MainWindow maine = new MainWindow();

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btn_exit;
    private keeptoo.KButton btn_signUp;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel icon;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passConfLabel;
    private javax.swing.JPasswordField passConfirm;
    private javax.swing.JLabel passLabel;
    private keeptoo.KGradientPanel signUpPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
